num1=float(input("Enter the first number: "))
num2=float(input("Enter the second number: "))
print("The first number is",num1,"and the second number is",num2)
print("The sum of the two numbers is",num1+num2)
print("The subtraction of the two numbers is",num1-num2)
#print("The division of the two numbers is",num1/num2)
print("The floor division of the two numbers is",num1//num2)
print("The multipication of the two numbers is",num1*num2)
print("The exponential of the two numbers is",num1**num2)
print("The modulas of the two numbers is",num1%num2)