file = open("index.txt","w")
file.write("Hello this is a new file. ")
file.write("Created by a human")
file.write(", living his/her life.")
file.close()
file = open("index.txt","a")
file.write('While having a depreviating sleep schedule')
file.close()
goal=input('Enter your goal: ')
file = open("index.txt","a")
file.write('\n'+goal+'\n')
file.close()